# 03 - Exploratory Data Analysis

Ce notebook répond aux premières questions métier :
- quel est le profil global du marché analysé ?
- quelles langues et quels pays dominent ?
- quels films performent le plus en revenu, popularité ou ROI ?

In [2]:
from pathlib import Path
import sys
from collections import Counter
import pandas as pd
import plotly.express as px

ROOT_DIR = Path.cwd()
if ROOT_DIR.name == 'notebooks':
    ROOT_DIR = ROOT_DIR.parent

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

PROCESSED_PATH = ROOT_DIR / 'data' / 'processed' / 'movies_clean.csv'
df = pd.read_csv(PROCESSED_PATH, parse_dates=['release_date'])
print(df.shape)

(946, 43)

In [3]:
df.head()

,tmdb_id,imdb_id,title,original_title,overview,release_date,status,genres,keywords,director,...,num_genres,genre_animation,genre_adventure,genre_family,genre_drama,genre_fantasy,genre_comedy,genre_action,success_score,success_label
0,150540,tt2096673,Inside Out,Inside Out,"When 11-year-old Riley moves to a new city, he...",2015-06-17,Released,"Adventure, Animation, Comedy, Drama, Family","dreams, san francisco, california, minnesota, ...",Pete Docter,...,5,1,1,1,1,0,1,0,6.167926,1
1,105864,tt1979388,The Good Dinosaur,The Good Dinosaur,An epic journey into the world of dinosaurs wh...,2015-11-14,Released,"Adventure, Animation, Family","friendship, tyrannosaurus rex, cartoon, friend...",Peter Sohn,...,3,1,1,1,0,0,0,0,4.225160,1
2,483685,tt5265536,Tokyo Ghoul: Jack,東京喰種トーキョーグール【JACK】,"Who needs school, who needs baseball, and who ...",2015-09-05,Released,"Action, Animation, Drama, Horror","monster, gore, prequel, tragedy, school, based...",Soichi Shimada,...,4,1,0,0,1,0,0,1,2.959014,1
3,228161,tt2224026,Home,Home,When Earth is taken over by the overly-confide...,2015-03-18,Released,"Animation, Comedy, Family, Fantasy, Science Fi...","spacecraft, villain, alien, space, alien invas...",Tim Johnson,...,5,1,0,1,0,1,1,0,4.512820,1
4,159824,tt2510894,Hotel Transylvania 2,Hotel Transylvania 2,When the old-old-old-fashioned vampire Vlad ar...,2015-09-21,Released,"Animation, Comedy, Family, Fantasy","hotel, witch, skeleton, magic, transylvania, t...",Genndy Tartakovsky,...,4,1,0,1,0,1,1,0,5.972412,1

In [1]:
pd.set_option('display.max_columns', None)
df.head()

NameError: name 'pd' is not defined

In [4]:
df.columns

Index(['tmdb_id', 'imdb_id', 'title', 'original_title', 'overview',
       'release_date', 'status', 'genres', 'keywords', 'director', 'top_cast',
       'budget', 'revenue', 'runtime', 'vote_average', 'vote_count',
       'popularity', 'original_language', 'production_country', 'adult',
       'video', 'omdb_error', 'roi', 'is_animation', 'release_year',
       'release_month', 'release_quarter', 'is_holiday_window', 'budget_musd',
       'revenue_musd', 'profit_musd', 'vote_count_log', 'popularity_log',
       'num_genres', 'genre_animation', 'genre_adventure', 'genre_family',
       'genre_drama', 'genre_fantasy', 'genre_comedy', 'genre_action',
       'success_score', 'success_label'],
      dtype='object')

In [ ]:
df[['tmdb_id', 'imdb_id', 'title', 'original_title', 'overview','release_date', 'status', 'genres', 'keywords', 'director', 'top_cast',
       'budget', 'revenue', 'runtime', 'vote_average', 'vote_count']].head()

,tmdb_id,imdb_id,title,original_title,overview,release_date,status,genres,keywords,director,top_cast,budget,revenue,runtime,vote_average,vote_count
0,150540,tt2096673,Inside Out,Inside Out,"When 11-year-old Riley moves to a new city, he...",2015-06-17,Released,"Adventure, Animation, Comedy, Drama, Family","dreams, san francisco, california, minnesota, ...",Pete Docter,"Amy Poehler, Phyllis Smith, Richard Kind, Bill...",175000000,857611174,95,7.910,23421
1,105864,tt1979388,The Good Dinosaur,The Good Dinosaur,An epic journey into the world of dinosaurs wh...,2015-11-14,Released,"Adventure, Animation, Family","friendship, tyrannosaurus rex, cartoon, friend...",Peter Sohn,"Frances McDormand, Raymond Ochoa, Jeffrey Wrig...",175000000,332207671,93,6.742,5980
2,483685,tt5265536,Tokyo Ghoul: Jack,東京喰種トーキョーグール【JACK】,"Who needs school, who needs baseball, and who ...",2015-09-05,Released,"Action, Animation, Drama, Horror","monster, gore, prequel, tragedy, school, based...",Soichi Shimada,"Saori Hayami, Daisuke Namikawa, Ryohei Kimura,...",0,0,30,7.620,96
3,228161,tt2224026,Home,Home,When Earth is taken over by the overly-confide...,2015-03-18,Released,"Animation, Comedy, Family, Fantasy, Science Fi...","spacecraft, villain, alien, space, alien invas...",Tim Johnson,"Jim Parsons, Rihanna, Steve Martin, Jennifer L...",135000000,368871007,94,6.788,4216
4,159824,tt2510894,Hotel Transylvania 2,Hotel Transylvania 2,When the old-old-old-fashioned vampire Vlad ar...,2015-09-21,Released,"Animation, Comedy, Family, Fantasy","hotel, witch, skeleton, magic, transylvania, t...",Genndy Tartakovsky,"Adam Sandler, Andy Samberg, Selena Gomez, Kevi...",80000000,473200000,89,6.763,6114

In [6]:
df[['popularity', 'original_language', 'production_country', 'adult',
       'video', 'omdb_error', 'roi', 'is_animation', 'release_year',
       'release_month', 'release_quarter', 'is_holiday_window', 'budget_musd',
       'revenue_musd', 'profit_musd', 'vote_count_log', 'popularity_log']].head()

,popularity,original_language,production_country,adult,video,omdb_error,roi,is_animation,release_year,release_month,release_quarter,is_holiday_window,budget_musd,revenue_musd,profit_musd,vote_count_log,popularity_log
0,22.8751,en,US,False,False,OMDb request failed: 401 Client Error: Unautho...,4.900635,1,2015,6,2,1,175.0,857.611174,682.611174,10.061431,3.172836
1,11.6763,en,US,False,False,OMDb request failed: 401 Client Error: Unautho...,1.898330,1,2015,11,4,1,175.0,332.207671,157.207671,8.696343,2.539734
2,10.6121,ja,JP,False,False,OMDb request failed: 401 Client Error: Unautho...,0.000000,1,2015,9,3,0,0.0,0.000000,0.000000,4.574711,2.452048
3,8.2824,en,US,False,False,OMDb request failed: 401 Client Error: Unautho...,2.732378,1,2015,3,1,0,135.0,368.871007,233.871007,8.346879,2.228120
4,7.0118,en,US,False,False,OMDb request failed: 401 Client Error: Unautho...,5.915000,1,2015,9,3,0,80.0,473.200000,393.200000,8.718500,2.080915

In [7]:
df[['num_genres', 'genre_animation', 'genre_adventure', 'genre_family',
       'genre_drama', 'genre_fantasy', 'genre_comedy', 'genre_action',
       'success_score', 'success_label']].head()

,num_genres,genre_animation,genre_adventure,genre_family,genre_drama,genre_fantasy,genre_comedy,genre_action,success_score,success_label
0,5,1,1,1,1,0,1,0,6.167926,1
1,3,1,1,1,0,0,0,0,4.225160,1
2,4,1,0,0,1,0,0,1,2.959014,1
3,5,1,0,1,0,1,1,0,4.512820,1
4,4,1,0,1,0,1,1,0,5.972412,1

In [29]:
df[['title', 'profit_musd']].head(20).sort_values(by='profit_musd',ascending=False)

                                             title  profit_musd
6                                          Minions  1085.457503
0                                       Inside Out   682.611174
4                             Hotel Transylvania 2   393.200000
5         The SpongeBob Movie: Sponge Out of Water   251.186032
3                                             Home   233.871007
1                                The Good Dinosaur   157.207671
13                               The Peanuts Movie   147.233113
8           Alvin and the Chipmunks: The Road Chip   143.755553
17                           Shaun the Sheep Movie    81.209378
9                  Dragon Ball Z: Resurrection 'F'    56.768190
15          Detective Conan: Sunflowers of Inferno    52.920296
14                           The Boy and the Beast    49.714378
7                         Boruto: Naruto the Movie    38.362448
10                               The Little Prince    37.281211
11  Pokémon the Movie: Hoopa and the Clash of Ages    21.815482
18               Ghost in the Shell: The New Movie     1.713406
2                                Tokyo Ghoul: Jack     0.000000
12                         Regular Show: The Movie    -3.000000
16           Doraemon: Nobita and the Space Heroes   -13.897700
19                                   Strange Magic   -86.396547

In [ ]:
main = df[['tmdb_id', 'imdb_id', 'title', 'original_title','release_date','genres',
            'budget', 'revenue', 'runtime', 'vote_average', 'vote_count',
            'original_language', 'production_country','roi', 'release_year','budget_musd',
       'revenue_musd', 'profit_musd','success_score']]

In [9]:
main.head()

,tmdb_id,imdb_id,title,original_title,release_date,genres,budget,budget,revenue,runtime,vote_average,vote_count,original_language,production_country,roi,release_year,budget_musd,revenue_musd,profit_musd,success_score
0,150540,tt2096673,Inside Out,Inside Out,2015-06-17,"Adventure, Animation, Comedy, Drama, Family",175000000,175000000,857611174,95,7.910,23421,en,US,4.900635,2015,175.0,857.611174,682.611174,6.167926
1,105864,tt1979388,The Good Dinosaur,The Good Dinosaur,2015-11-14,"Adventure, Animation, Family",175000000,175000000,332207671,93,6.742,5980,en,US,1.898330,2015,175.0,332.207671,157.207671,4.225160
2,483685,tt5265536,Tokyo Ghoul: Jack,東京喰種トーキョーグール【JACK】,2015-09-05,"Action, Animation, Drama, Horror",0,0,0,30,7.620,96,ja,JP,0.000000,2015,0.0,0.000000,0.000000,2.959014
3,228161,tt2224026,Home,Home,2015-03-18,"Animation, Comedy, Family, Fantasy, Science Fi...",135000000,135000000,368871007,94,6.788,4216,en,US,2.732378,2015,135.0,368.871007,233.871007,4.512820
4,159824,tt2510894,Hotel Transylvania 2,Hotel Transylvania 2,2015-09-21,"Animation, Comedy, Family, Fantasy",80000000,80000000,473200000,89,6.763,6114,en,US,5.915000,2015,80.0,473.200000,393.200000,5.972412

In [22]:
px.histogram(
    df,
    x='release_year',)

In [11]:
kpis = {
    'rows': len(df),
    'date_min': str(df['release_date'].min().date()),
    'date_max': str(df['release_date'].max().date()),
    'avg_rating': round(df['vote_average'].mean(), 2),
    'avg_roi': round(df['roi'].mean(), 2),
    'total_revenue_billion': round(df['revenue'].sum() / 1_000_000_000, 2),
}
kpis

{'rows': 946,
 'date_min': '2015-01-01',
 'date_max': '2025-12-16',
 'avg_rating': 7.04,
 'avg_roi': 1.1,
 'total_revenue_billion': 54.37}

In [12]:
year_counts = df['release_date'].dt.year.value_counts().sort_index().reset_index()
year_counts.columns = ['release_year', 'n_titles']
px.bar(year_counts, x='release_year', y='n_titles', title='Nombre de films par an')

In [13]:
language_counts = df['original_language'].value_counts().head(10).reset_index()
language_counts.columns = ['original_language', 'n_titles']
px.bar(language_counts, x='original_language', y='n_titles', title='Top 10 langues originales')

In [14]:
country_counts = df['production_country'].value_counts().head(10).reset_index()
country_counts.columns = ['production_country', 'n_titles']
px.bar(country_counts, x='production_country', y='n_titles', title='Top 10 pays de production')

In [15]:
genre_counter = Counter()
for value in df['genres'].dropna():
    for genre in [chunk.strip() for chunk in str(value).split(',') if chunk.strip()]:
        genre_counter[genre] += 1

genre_df = pd.DataFrame(genre_counter.items(), columns=['genre', 'count']).sort_values('count', ascending=False).head(12)
px.bar(genre_df, x='genre', y='count', title='Genres les plus fréquents')

In [16]:
px.scatter(
    df,
    x='budget',
    y='revenue',
    color='original_language',
    hover_name='title',
    title='Relation budget / revenue'
)

In [17]:
top_revenue = df[['title', 'release_date', 'revenue', 'budget', 'vote_average', 'popularity']].sort_values('revenue', ascending=False).head(15)
top_revenue

,title,release_date,revenue,budget,vote_average,popularity
912,Ne Zha 2,2025-01-29,2259822417,80000000,8.145,27.8013
909,Zootopia 2,2025-11-26,1868208796,150000000,7.639,89.6629
843,Inside Out 2,2024-06-11,1698863816,200000000,7.500,30.2836
388,The Lion King,2019-07-12,1662020819,260000000,7.098,11.2636
387,Frozen II,2019-11-20,1453683476,150000000,7.231,11.3653
769,The Super Mario Bros. Movie,2023-04-05,1360879735,100000000,7.597,42.4097
298,Incredibles 2,2018-06-14,1243225667,200000000,7.451,11.0582
6,Minions,2015-06-17,1159457503,74000000,6.419,5.9212
384,Toy Story 4,2019-06-19,1073841394,175000000,7.466,14.9123
845,Moana 2,2024-11-21,1059242164,150000000,7.000,26.6411
200,Despicable Me 3,2017-06-15,1034800131,80000000,6.467,6.5920
107,Finding Dory,2016-06-16,1029266989,200000000,7.040,7.6669
101,Zootopia,2016-02-11,1025521689,150000000,7.800,24.7268
847,Despicable Me 4,2024-06-20,972021410,100000000,6.987,22.5436
674,Minions: The Rise of Gru,2022-06-29,940203765,85000000,7.269,10.9193

In [18]:
top_roi = df.loc[df['budget'] > 0, ['title', 'release_date', 'budget', 'revenue', 'roi']].sort_values('roi', ascending=False).head(15)
top_roi

,title,release_date,budget,revenue,roi
332,Dragon Ball Super: Broly,2018-12-14,1000000,125002821,125.002821
100,Your Name.,2016-08-26,7500000,405320132,54.042684
913,Chainsaw Man - The Movie: Reze Arc,2025-09-19,4100000,174502910,42.561685
908,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,20000000,733030221,36.651511
385,Ne Zha,2019-07-26,22000000,742718496,33.759932
486,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,2020-10-16,15700000,523542183,33.346636
912,Ne Zha 2,2025-01-29,80000000,2259822417,28.247780
676,Suzume,2022-11-11,13000000,314992206,24.230170
856,HAIKYU!! The Dumpster Battle,2024-02-16,5000000,100255784,20.051157
138,Big Fish & Begonia,2016-07-08,4531653,84552250,18.658147
389,Weathering with You,2019-07-19,11100000,192729404,17.363009
6,Minions,2015-06-17,74000000,1159457503,15.668345
21,Monkey King: Hero Is Back,2015-07-10,10000000,153000000,15.300000
769,The Super Mario Bros. Movie,2023-04-05,100000000,1360879735,13.608797
200,Despicable Me 3,2017-06-15,80000000,1034800131,12.935002